In [1]:
import pandas as pd

df = pd.read_csv("renewable_energy.csv")
df.head()

   Country         Region  Population  %Renewable  CO2_Emissions
0    Nepal           Asia          30          89            0.3
1    Kenya         Africa          54          76            0.5
2   Brazil  South America         213          45            2.1
3    India           Asia        1400          24            1.9
4  Germany         Europe          83          48            9.6

In [2]:
df.tail(3)

   Country         Region  Population  %Renewable  CO2_Emissions
7  Nigeria         Africa         206          17            0.6
8  Vietnam           Asia          98          64            1.2
9   Mexico  North America         128          41            3.9

In [6]:
df.values

array([['Nepal', 'Asia', 30, 89, 0.3],
       ['Kenya', 'Africa', 54, 76, 0.5],
       ['Brazil', 'South America', 213, 45, 2.1],
       ['India', 'Asia', 1400, 24, 1.9],
       ['Germany', 'Europe', 83, 48, 9.6],
       ['Norway', 'Europe', 5, 98, 0.1],
       ['Australia', 'Oceania', 26, 30, 15.3],
       ['Nigeria', 'Africa', 206, 17, 0.6],
       ['Vietnam', 'Asia', 98, 64, 1.2],
       ['Mexico', 'North America', 128, 41, 3.9]], dtype=object)

In [7]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [8]:
df.describe

<bound method NDFrame.describe of      Country         Region  Population  %Renewable  CO2_Emissions
0      Nepal           Asia          30          89            0.3
1      Kenya         Africa          54          76            0.5
2     Brazil  South America         213          45            2.1
3      India           Asia        1400          24            1.9
4    Germany         Europe          83          48            9.6
5     Norway         Europe           5          98            0.1
6  Australia        Oceania          26          30           15.3
7    Nigeria         Africa         206          17            0.6
8    Vietnam           Asia          98          64            1.2
9     Mexico  North America         128          41            3.9>

In [9]:
df.columns

Index(['Country', 'Region', 'Population', '%Renewable', 'CO2_Emissions'], dtype='str')

In [10]:
df.rename(columns={'Country': 'Countries'}, inplace=True)

In [11]:
df.columns

Index(['Countries', 'Region', 'Population', '%Renewable', 'CO2_Emissions'], dtype='str')