In [1]:
#Purpose
#analysing rising sea level trends in the Pacific and assessing the projected impact on low-lying nations

#Step 0 Importing Libraries
library(tidyverse)
library(ggplot2)
library(reshape2)

Warning message:
"package 'ggplot2' was built under R version 4.5.3"
── Attaching core tidyverse packages ───────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Warning message:
"package 'reshape2' was built under R version 4.5.3"

Attaching package: 'reshape2'


The following object is masked from 'package:tidyr':

    smiths

In [2]:
#Step 0 Importing dataset and inspection
main_df <- read.csv("USStationsLinearSeaLevelTrends.csv")

In [3]:
glimpse(main_df) #Transposed view of entire dataset, running horizontal instead of vertical

Rows: 149
Columns: 12
$ Station.ID               <int> 1611400, 1612340, 1612480, 1615680, 1617433, …
$ Station.Name             <chr> "Nawiliwili, HI", "Honolulu, HI", "Mokuoloe, …
$ First.Year               <int> 1955, 1905, 1957, 1947, 1988, 1927, 1947, 199…
$ Last.Year                <int> 2025, 2025, 2025, 2025, 2025, 2025, 2025, 202…
$ Year.Range               <int> 71, 121, 69, 79, 38, 99, 79, 33, 17, 80, 76, …
$ X..Complete              <int> 100, 100, 84, 96, 92, 85, 96, 96, 95, 99, 94,…
$ MSL.Trends..mm.yr.       <dbl> 1.90, 1.57, 1.79, 2.30, 3.81, 3.15, 1.58, 5.3…
$ X....95..CI..mm.yr.      <dbl> 0.37, 0.19, 0.47, 0.36, 0.96, 0.27, 0.36, 2.8…
$ MSL.Trend..ft.century.   <dbl> 0.62, 0.51, 0.59, 0.75, 1.25, 1.03, 0.52, 1.7…
$ X....95..CI..ft.century. <dbl> 0.12, 0.06, 0.16, 0.12, 0.31, 0.09, 0.12, 0.9…
$ Latitude                 <dbl> 21.9544, 21.3033, 21.4331, 20.8949, 20.0366, …
$ Longitude                <dbl> -159.3561, -157.8645, -157.7900, -156.4690, -…

In [4]:
head(main_df) #irst 5 rows of the Relative Sea Level Trends for Honolulu, Hawaii

  Station.ID Station.Name   First.Year Last.Year Year.Range X..Complete
1 1611400    Nawiliwili, HI 1955       2025       71        100
2 1612340    Honolulu, HI   1905       2025      121        100
3 1612480    Mokuoloe, HI   1957       2025       69         84
4 1615680    Kahului, HI    1947       2025       79         96
5 1617433    Kawaihae, HI   1988       2025       38         92
6 1617760    Hilo, HI       1927       2025       99         85
  MSL.Trends..mm.yr. X....95..CI..mm.yr. MSL.Trend..ft.century.
1 1.90               0.37                0.62
2 1.57               0.19                0.51
3 1.79               0.47                0.59
4 2.30               0.36                0.75
5 3.81               0.96                1.25
6 3.15               0.27                1.03
  X....95..CI..ft.century. Latitude Longitude
1 0.12                     21.9544  -159.3561
2 0.06                     21.3033  -157.8645
3 0.16                     21.4331  -157.7900
4 0.12                     20.8949  -156.4690
5 0.31                     20.0366  -155.8294
6 0.09                     19.7303  -155.0556

In [ ]:
#The dataset I've used contains 149 US tide gauge stations
#Columns include: Station.ID, Station.Name, First.Year, Last.Year, Year.Range, X..Complete, 
#MSL.Trends..mm.yr., X....95..CI..mm.yr.
#MSL.Trend.ft.century.
#X....95..CI..ft.century.
#Latitude
#Longitude

In [6]:
#Step 1: Transforming into wide format
#Step 1.1 - Building the Mean Sea Level Matrix
unique(main_df$Station.Name) #Checking all the unique region names in the dataset

  [1] "Nawiliwili, HI"                   "Honolulu, HI"
  [3] "Mokuoloe, HI"                     "Kahului, HI"
  [5] "Kawaihae, HI"                     "Hilo, HI"
  [7] "Midway Atoll, "                   "Apra Harbor, Guam, "
  [9] "Pago Pago, American Samoa, "      "Kwajalein, Marshall Islands, "
 [11] "Wake Island, Pacific Ocean, "     "Biological Station, Bermuda, "
 [13] "St. Georges, Bermuda, "           "Eastport, ME"
 [15] "Cutler, ME"                       "Bar Harbor, ME"
 [17] "Portland, ME"                     "Seavey Island, ME"
 [19] "Fort Point, NH"                   "Boston, MA"
 [21] "Woods Hole, MA"                   "Nantucket Island, MA"
 [23] "Newport, RI"                      "Providence, RI"
 [25] "New London, CT"                   "Bridgeport, CT"
 [27] "Montauk, NY"                      "Kings Point, NY"
 [29] "The Battery, NY"                  "Bergen Point, NY"
 [31] "Sandy Hook, NJ"                   "Atlantic City, NJ"
 [33] "Cape May, NJ"                     "Philadelphia, PA"
 [35] "Reedy Point, DE"                  "Lewes, DE"
 [37] "Ocean City, MD"                   "Cambridge, MD"
 [39] "Tolchester Beach, MD"             "Chesapeake City, MD"
 [41] "Baltimore, MD"                    "Annapolis, MD"
 [43] "Solomons Island, MD"              "Washington, DC"
 [45] "Wachapreague, VA"                 "Kiptopeke, VA"
 [47] "Dahlgren, VA"                     "Lewisetta, VA"
 [49] "Windmill Point, VA"               "Yorktown, VA"
 [51] "Sewells Point, VA"                "Chesapeake Bay Bridge Tunnel, VA"
 [53] "Chesapeake Channel, VA"           "Duck, NC"
 [55] "Oregon Inlet Marina, NC"          "Beaufort, NC"
 [57] "Wilmington, NC"                   "Springmaid Pier, SC"
 [59] "Charleston, SC"                   "Fort Pulaski, GA"
 [61] "Fernandina Beach, FL"             "Mayport, FL"
 [63] "Port Canaveral, FL"               "Lake Worth Pier, FL"
 [65] "Virginia Key, FL"                 "Vaca Key, FL"
 [67] "Key West, FL"                     "Naples, FL"
 [69] "Fort Myers, FL"                   "Port Manatee, FL"
 [71] "St. Petersburg, FL"               "Old Port Tampa, FL"
 [73] "East Bay, FL"                     "Clearwater Beach, FL"
 [75] "Cedar Key, FL"                    "Apalachicola, FL"
 [77] "Panama City, FL"                  "Panama City Beach, FL"
 [79] "Pensacola, FL"                    "Dauphin Island, AL"
 [81] "Mobile State Docks, AL"           "Bay Waveland, MS"
 [83] "Grand Isle, LA"                   "New Canal, LA"
 [85] "Sabine Pass, TX"                  "Morgans Point, TX"
 [87] "Texas Point, TX"                  "Eagle Point, TX"
 [89] "Galveston Bay Entrance, TX"       "Galveston Pier 21, TX"
 [91] "Galveston Pleasure Pier, TX"      "Freeport, TX"
 [93] "Freeport Harbor, TX"              "Rockport, TX"
 [95] "Packery Channel, TX"              "Corpus Christi, TX"
 [97] "Port Mansfield, TX"               "South Padre Island, TX"
 [99] "Port Isabel, TX"                  "San Diego, CA"
[101] "La Jolla, CA"                     "Los Angeles, CA"
[103] "Santa Monica, CA"                 "Santa Barbara, CA"
[105] "Port San Luis, CA"                "Monterey, CA"
[107] "San Francisco, CA"                "Redwood City, CA"
[109] "Alameda, CA"                      "Richmond, CA"
[111] "Point Reyes, CA"                  "Port Chicago, CA"
[113] "Arena Cove, CA"                   "North Spit, CA"
[115] "Crescent City, CA"                "Port Orford, OR"
[117] "Charleston, OR"                   "South Beach, OR"
[119] "Garibaldi, OR"                    "Astoria, OR"
[121] "Toke Point, WA"                   "Neah Bay, WA"
[123] "Port Angeles, WA"                 "Port Townsend, WA"
[125] "Seattle, WA"                      "Cherry Point, WA"
[127] "Friday Harbor, WA"                "Ketchikan, AK"
[129] "Sitka, AK"                        "Juneau, AK"
[131] "Skagway, AK"                      "Yakutat, AK"
[133] "Cordova, AK"                      "Valdez, AK"
[135] "Seward, AK"                       "Seldovia, AK"
[137] "Nikiski, AK"                      "Anchorage, AK"
[139] "Kodiak Island, AK"                "Sand Point, AK"
[141] "Adak Island, AK"                  "Unalaska, AK"
[143] "Port Moller, AK"                  "Nome, AK"
[145] "Prudhoe Bay, AK"                  "Lime Tree Bay, VI"
[147] "Charlotte Amalie, VI"             "San Juan, PR"
[149] "Magueyes Island, PR"

In [8]:
main_df$MSL.Trends..mm.yr. #Checking the Mean Sea Level trends in mm per year for each station
#This column asks how quickly the sea is threatening each of the station's location

  [1]   1.90   1.57   1.79   2.30   3.81   3.15   1.58   5.37  15.48   2.12
 [11]   2.15   2.21   2.19   2.33   2.34   2.48   1.97   2.21   2.04   2.97
 [21]   3.15   4.14   2.98   2.64   2.94   3.43   3.60   2.74   2.95   4.72
 [31]   4.28   4.25   5.10   3.15   3.94   3.78   5.25   4.05   4.31   4.47
 [41]   3.31   3.87   4.11   3.54   5.68   4.02   5.70   5.93   6.47   4.84
 [51]   4.84   5.92   6.15   4.94   5.50   3.62   2.80   3.36   3.51   3.67
 [61]   2.31   2.92   6.41   4.12   3.20   4.19   2.64   3.35   3.62   5.46
 [71]   3.13   6.04   5.50   4.36   2.39   3.05   3.08   4.86   2.72   4.37
 [81]   4.62   4.59   9.13   5.99   6.16   3.80   5.76  12.19   6.59   6.63
 [91]   6.62   4.21   3.51   6.04   6.13   5.48   3.73   4.09   4.35   2.22
[101]   2.02   1.07   1.52   1.05   0.99   1.77   1.99   2.74   0.94   3.35
[111]   2.15   1.96   1.15   5.08  -0.76  -0.05   1.12   1.75   2.44  -0.15
[121]   0.45  -1.70   0.46   1.82   2.09  -0.04   1.19  -0.36  -2.46 -13.51
[131] -18.13 -15.40  -0.54  -8.77  -3.08  -9.51 -10.12  -0.69  -9.53   2.04
[141]  -2.30  -4.18   4.02   4.15   4.28   2.71   2.21   2.16   2.06

In [12]:
sea_matrix <- matrix(
    main_df$MSL.Trends..mm.yr, #Pulls all the 149 values from the MSL.Trends..mm.yr column
    nrow = 149 #Total rows of the dataset
    )

rownames(sea_matrix) <- main_df$Station.Name #Assigning station names as row labels
colnames(sea_matrix) <- "MSL_Trend_mm_yr"
         
print(sea_matrix) #Viewing the matrix

#The reason why I chose to do only station.name and MSL_Trend_mm_yr is because I want to see the correlation betwen each station's MSL.

                                 MSL_Trend_mm_yr
Nawiliwili, HI                              1.90
Honolulu, HI                                1.57
Mokuoloe, HI                                1.79
Kahului, HI                                 2.30
Kawaihae, HI                                3.81
Hilo, HI                                    3.15
Midway Atoll,                               1.58
Apra Harbor, Guam,                          5.37
Pago Pago, American Samoa,                 15.48
Kwajalein, Marshall Islands,                2.12
Wake Island, Pacific Ocean,                 2.15
Biological Station, Bermuda,                2.21
St. Georges, Bermuda,                       2.19
Eastport, ME                                2.33
Cutler, ME                                  2.34
Bar Harbor, ME                              2.48
Portland, ME                                1.97
Seavey Island, ME                           2.21
Fort Point, NH                              2.04
Boston, MA                                  2.97
Woods Hole, MA                              3.15
Nantucket Island, MA                        4.14
Newport, RI                                 2.98
Providence, RI                              2.64
New London, CT                              2.94
Bridgeport, CT                              3.43
Montauk, NY                                 3.60
Kings Point, NY                             2.74
The Battery, NY                             2.95
Bergen Point, NY                            4.72
Sandy Hook, NJ                              4.28
Atlantic City, NJ                           4.25
Cape May, NJ                                5.10
Philadelphia, PA                            3.15
Reedy Point, DE                             3.94
Lewes, DE                                   3.78
Ocean City, MD                              5.25
Cambridge, MD                               4.05
Tolchester Beach, MD                        4.31
Chesapeake City, MD                         4.47
Baltimore, MD                               3.31
Annapolis, MD                               3.87
Solomons Island, MD                         4.11
Washington, DC                              3.54
Wachapreague, VA                            5.68
Kiptopeke, VA                               4.02
Dahlgren, VA                                5.70
Lewisetta, VA                               5.93
Windmill Point, VA                          6.47
Yorktown, VA                                4.84
Sewells Point, VA                           4.84
Chesapeake Bay Bridge Tunnel, VA            5.92
Chesapeake Channel, VA                      6.15
Duck, NC                                    4.94
Oregon Inlet Marina, NC                     5.50
Beaufort, NC                                3.62
Wilmington, NC                              2.80
Springmaid Pier, SC                         3.36
Charleston, SC                              3.51
Fort Pulaski, GA                            3.67
Fernandina Beach, FL                        2.31
Mayport, FL                                 2.92
Port Canaveral, FL                          6.41
Lake Worth Pier, FL                         4.12
Virginia Key, FL                            3.20
Vaca Key, FL                                4.19
Key West, FL                                2.64
Naples, FL                                  3.35
Fort Myers, FL                              3.62
Port Manatee, FL                            5.46
St. Petersburg, FL                          3.13
Old Port Tampa, FL                          6.04
East Bay, FL                                5.50
Clearwater Beach, FL                        4.36
Cedar Key, FL                               2.39
Apalachicola, FL                            3.05
Panama City, FL                             3.08
Panama City Beach, FL                       4.86
Pensacola, FL                               2.72
Dauphin Island, AL                          4.37
Mobile State Docks, AL                      4.62
Bay Waveland, MS                            4.59
Grand Isle, LA                              9.13
New Canal, LA                               5.99
Sabine Pass, TX                             6.16
Morgans Point, TX                           3.80
Texas Point, TX                             5.76
Eagle Point, TX                            12.19
Galveston Bay Entrance, TX                  6.59
Galveston Pier 21, TX                       6.63
Galveston Pleasure Pier, TX                 6.62
Freeport, TX                                4.21
Freeport Harbor, TX                         3.51
Rockport, TX                                6.04
Packery Channel, TX                         6.13
Corpus Christi, TX                          5.48
Port Mansfield, TX                          3.73
South Padre Island, TX                      4.09
Port Isabel, TX                             4.35
San Diego, CA                               2.22
La Jolla, CA                                2.02
Los Angeles, CA                             1.07
Santa Monica, CA                            1.52
Santa Barbara, CA                           1.05
Port San Luis, CA                           0.99
Monterey, CA                                1.77
San Francisco, CA                           1.99
Redwood City, CA                            2.74
Alameda, CA                                 0.94
Richmond, CA                                3.35
Point Reyes, CA                             2.15
Port Chicago, CA                            1.96
Arena Cove, CA                              1.15
North Spit, CA                              5.08
Crescent City, CA                          -0.76
Port Orford, OR                            -0.05
Charleston, OR                              1.12
South Beach, OR                             1.75
Garibaldi, OR                               2.44
Astoria, OR                                -0.15
Toke Point, WA                              0.45
Neah Bay, WA                               -1.70
Port Angeles, WA                            0.46
Port Townsend, WA                           1.82
Seattle, WA                                 2.09
Cherry Point, WA                           -0.04
Friday Harbor, WA                           1.19
Ketchikan, AK                              -0.36
Sitka, AK                                  -2.46
Juneau, AK                                -13.51
Skagway, AK                               -18.13
Yakutat, AK                               -15.40
Cordova, AK                                -0.54
Valdez, AK                                 -8.77
Seward, AK                                 -3.08
Seldovia, AK                               -9.51
Nikiski, AK                               -10.12
Anchorage, AK                              -0.69
Kodiak Island, AK                          -9.53
Sand Point, AK                              2.04
Adak Island, AK                            -2.30
Unalaska, AK                               -4.18
Port Moller, AK                             4.02
Nome, AK                                    4.15
Prudhoe Bay, AK                             4.28
Lime Tree Bay, VI                           2.71
Charlotte Amalie, VI                        2.21
San Juan, PR                                2.16
Magueyes Island, PR                         2.06

In [13]:
#Step 1.2 Transposing the Matrix into Wide Format
wide_matrix <- t(sea_matrix) #Station names become columns and MSL_Trend_mm_yr become rows. 

print(wide_matrix) #The wide format matrix contains 149 columns (one per station) which makes it difficult to display in full, however the structure is correct with stations as columns and MSL_Trend_mm_yr as the single row.

                Nawiliwili, HI Honolulu, HI Mokuoloe, HI Kahului, HI
MSL_Trend_mm_yr            1.9         1.57         1.79         2.3
                Kawaihae, HI Hilo, HI Midway Atoll,  Apra Harbor, Guam,
MSL_Trend_mm_yr         3.81     3.15           1.58                5.37
                Pago Pago, American Samoa,  Kwajalein, Marshall Islands,
MSL_Trend_mm_yr                       15.48                          2.12
                Wake Island, Pacific Ocean,  Biological Station, Bermuda,
MSL_Trend_mm_yr                         2.15                          2.21
                St. Georges, Bermuda,  Eastport, ME Cutler, ME Bar Harbor, ME
MSL_Trend_mm_yr                   2.19         2.33       2.34           2.48
                Portland, ME Seavey Island, ME Fort Point, NH Boston, MA
MSL_Trend_mm_yr         1.97              2.21           2.04       2.97
                Woods Hole, MA Nantucket Island, MA Newport, RI Providence, RI
MSL_Trend_mm_yr           3.15                 4.14        2.98           2.64
                New London, CT Bridgeport, CT Montauk, NY Kings Point, NY
MSL_Trend_mm_yr           2.94           3.43         3.6            2.74
                The Battery, NY Bergen Point, NY Sandy Hook, NJ
MSL_Trend_mm_yr            2.95             4.72           4.28
                Atlantic City, NJ Cape May, NJ Philadelphia, PA Reedy Point, DE
MSL_Trend_mm_yr              4.25          5.1             3.15            3.94
                Lewes, DE Ocean City, MD Cambridge, MD Tolchester Beach, MD
MSL_Trend_mm_yr      3.78           5.25          4.05                 4.31
                Chesapeake City, MD Baltimore, MD Annapolis, MD
MSL_Trend_mm_yr                4.47          3.31          3.87
                Solomons Island, MD Washington, DC Wachapreague, VA
MSL_Trend_mm_yr                4.11           3.54             5.68
                Kiptopeke, VA Dahlgren, VA Lewisetta, VA Windmill Point, VA
MSL_Trend_mm_yr          4.02          5.7          5.93               6.47
                Yorktown, VA Sewells Point, VA Chesapeake Bay Bridge Tunnel, VA
MSL_Trend_mm_yr         4.84              4.84                             5.92
                Chesapeake Channel, VA Duck, NC Oregon Inlet Marina, NC
MSL_Trend_mm_yr                   6.15     4.94                     5.5
                Beaufort, NC Wilmington, NC Springmaid Pier, SC Charleston, SC
MSL_Trend_mm_yr         3.62            2.8                3.36           3.51
                Fort Pulaski, GA Fernandina Beach, FL Mayport, FL
MSL_Trend_mm_yr             3.67                 2.31        2.92
                Port Canaveral, FL Lake Worth Pier, FL Virginia Key, FL
MSL_Trend_mm_yr               6.41                4.12              3.2
                Vaca Key, FL Key West, FL Naples, FL Fort Myers, FL
MSL_Trend_mm_yr         4.19         2.64       3.35           3.62
                Port Manatee, FL St. Petersburg, FL Old Port Tampa, FL
MSL_Trend_mm_yr             5.46               3.13               6.04
                East Bay, FL Clearwater Beach, FL Cedar Key, FL
MSL_Trend_mm_yr          5.5                 4.36          2.39
                Apalachicola, FL Panama City, FL Panama City Beach, FL
MSL_Trend_mm_yr             3.05            3.08                  4.86
                Pensacola, FL Dauphin Island, AL Mobile State Docks, AL
MSL_Trend_mm_yr          2.72               4.37                   4.62
                Bay Waveland, MS Grand Isle, LA New Canal, LA Sabine Pass, TX
MSL_Trend_mm_yr             4.59           9.13          5.99            6.16
                Morgans Point, TX Texas Point, TX Eagle Point, TX
MSL_Trend_mm_yr               3.8            5.76           12.19
                Galveston Bay Entrance, TX Galveston Pier 21, TX
MSL_Trend_mm_yr                       6.59                  6.63
                Galveston Pleasure Pier, TX Freeport, TX Freeport Harbor, TX
MSL_Trend_mm_yr                        6.62         4.21                3.51
                Rockport, TX Packery Channel, TX Corpus Christi, TX
MSL_Trend_mm_yr         6.04                6.13               5.48
                Port Mansfield, TX South Padre Island, TX Port Isabel, TX
MSL_Trend_mm_yr               3.73                   4.09            4.35
                San Diego, CA La Jolla, CA Los Angeles, CA Santa Monica, CA
MSL_Trend_mm_yr          2.22         2.02            1.07             1.52
                Santa Barbara, CA Port San Luis, CA Monterey, CA
MSL_Trend_mm_yr              1.05              0.99         1.77
                San Francisco, CA Redwood City, CA Alameda, CA Richmond, CA
MSL_Trend_mm_yr              1.99             2.74        0.94         3.35
                Point Reyes, CA Port Chicago, CA Arena Cove, CA North Spit, CA
MSL_Trend_mm_yr            2.15             1.96           1.15           5.08
                Crescent City, CA Port Orford, OR Charleston, OR
MSL_Trend_mm_yr             -0.76           -0.05           1.12
                South Beach, OR Garibaldi, OR Astoria, OR Toke Point, WA
MSL_Trend_mm_yr            1.75          2.44       -0.15           0.45
                Neah Bay, WA Port Angeles, WA Port Townsend, WA Seattle, WA
MSL_Trend_mm_yr         -1.7             0.46              1.82        2.09
                Cherry Point, WA Friday Harbor, WA Ketchikan, AK Sitka, AK
MSL_Trend_mm_yr            -0.04              1.19         -0.36     -2.46
                Juneau, AK Skagway, AK Yakutat, AK Cordova, AK Valdez, AK
MSL_Trend_mm_yr     -13.51      -18.13       -15.4       -0.54      -8.77
                Seward, AK Seldovia, AK Nikiski, AK Anchorage, AK
MSL_Trend_mm_yr      -3.08        -9.51      -10.12         -0.69
                Kodiak Island, AK Sand Point, AK Adak Island, AK Unalaska, AK
MSL_Trend_mm_yr             -9.53           2.04            -2.3        -4.18
                Port Moller, AK Nome, AK Prudhoe Bay, AK Lime Tree Bay, VI
MSL_Trend_mm_yr            4.02     4.15            4.28              2.71
                Charlotte Amalie, VI San Juan, PR Magueyes Island, PR
MSL_Trend_mm_yr                 2.21         2.16                2.06

In [15]:
wide_matrix[, 1:6] #Previewing first 6 columns of the wide matrix to verify correct values

Nawiliwili, HI   Honolulu, HI   Mokuoloe, HI    Kahului, HI   Kawaihae, HI
          1.90           1.57           1.79           2.30           3.81
      Hilo, HI
          3.15

In [17]:
# Cross check against original data
head(main_df[, c("Station.Name", "MSL.Trends..mm.yr.")], 6)

  Station.Name   MSL.Trends..mm.yr.
1 Nawiliwili, HI 1.90
2 Honolulu, HI   1.57
3 Mokuoloe, HI   1.79
4 Kahului, HI    2.30
5 Kawaihae, HI   3.81
6 Hilo, HI       3.15

In [18]:
#Step 1.3 Scaling the wide_matrix
scaled_matrix <- scale(wide_matrix) #standardises all values to have a mean of 0 and standard deviation of 1. Without doing this first, high values of MSL.Trends..mm.yr will distort the correlation

print(scaled_matrix)

                Nawiliwili, HI Honolulu, HI Mokuoloe, HI Kahului, HI
MSL_Trend_mm_yr            NaN          NaN          NaN         NaN
                Kawaihae, HI Hilo, HI Midway Atoll,  Apra Harbor, Guam,
MSL_Trend_mm_yr          NaN      NaN            NaN                 NaN
                Pago Pago, American Samoa,  Kwajalein, Marshall Islands,
MSL_Trend_mm_yr                         NaN                           NaN
                Wake Island, Pacific Ocean,  Biological Station, Bermuda,
MSL_Trend_mm_yr                          NaN                           NaN
                St. Georges, Bermuda,  Eastport, ME Cutler, ME Bar Harbor, ME
MSL_Trend_mm_yr                    NaN          NaN        NaN            NaN
                Portland, ME Seavey Island, ME Fort Point, NH Boston, MA
MSL_Trend_mm_yr          NaN               NaN            NaN        NaN
                Woods Hole, MA Nantucket Island, MA Newport, RI Providence, RI
MSL_Trend_mm_yr            NaN                  NaN         NaN            NaN
                New London, CT Bridgeport, CT Montauk, NY Kings Point, NY
MSL_Trend_mm_yr            NaN            NaN         NaN             NaN
                The Battery, NY Bergen Point, NY Sandy Hook, NJ
MSL_Trend_mm_yr             NaN              NaN            NaN
                Atlantic City, NJ Cape May, NJ Philadelphia, PA Reedy Point, DE
MSL_Trend_mm_yr               NaN          NaN              NaN             NaN
                Lewes, DE Ocean City, MD Cambridge, MD Tolchester Beach, MD
MSL_Trend_mm_yr       NaN            NaN           NaN                  NaN
                Chesapeake City, MD Baltimore, MD Annapolis, MD
MSL_Trend_mm_yr                 NaN           NaN           NaN
                Solomons Island, MD Washington, DC Wachapreague, VA
MSL_Trend_mm_yr                 NaN            NaN              NaN
                Kiptopeke, VA Dahlgren, VA Lewisetta, VA Windmill Point, VA
MSL_Trend_mm_yr           NaN          NaN           NaN                NaN
                Yorktown, VA Sewells Point, VA Chesapeake Bay Bridge Tunnel, VA
MSL_Trend_mm_yr          NaN               NaN                              NaN
                Chesapeake Channel, VA Duck, NC Oregon Inlet Marina, NC
MSL_Trend_mm_yr                    NaN      NaN                     NaN
                Beaufort, NC Wilmington, NC Springmaid Pier, SC Charleston, SC
MSL_Trend_mm_yr          NaN            NaN                 NaN            NaN
                Fort Pulaski, GA Fernandina Beach, FL Mayport, FL
MSL_Trend_mm_yr              NaN                  NaN         NaN
                Port Canaveral, FL Lake Worth Pier, FL Virginia Key, FL
MSL_Trend_mm_yr                NaN                 NaN              NaN
                Vaca Key, FL Key West, FL Naples, FL Fort Myers, FL
MSL_Trend_mm_yr          NaN          NaN        NaN            NaN
                Port Manatee, FL St. Petersburg, FL Old Port Tampa, FL
MSL_Trend_mm_yr              NaN                NaN                NaN
                East Bay, FL Clearwater Beach, FL Cedar Key, FL
MSL_Trend_mm_yr          NaN                  NaN           NaN
                Apalachicola, FL Panama City, FL Panama City Beach, FL
MSL_Trend_mm_yr              NaN             NaN                   NaN
                Pensacola, FL Dauphin Island, AL Mobile State Docks, AL
MSL_Trend_mm_yr           NaN                NaN                    NaN
                Bay Waveland, MS Grand Isle, LA New Canal, LA Sabine Pass, TX
MSL_Trend_mm_yr              NaN            NaN           NaN             NaN
                Morgans Point, TX Texas Point, TX Eagle Point, TX
MSL_Trend_mm_yr               NaN             NaN             NaN
                Galveston Bay Entrance, TX Galveston Pier 21, TX
MSL_Trend_mm_yr                        NaN                   NaN
                Galveston Pleasure Pier, TX Freeport, TX Freeport Harbor, TX
MSL_Trend_mm_yr                         NaN          NaN                 NaN
                Rockport, TX Packery Channel, TX Corpus Christi, TX
MSL_Trend_mm_yr          NaN                 NaN                NaN
                Port Mansfield, TX South Padre Island, TX Port Isabel, TX
MSL_Trend_mm_yr                NaN                    NaN             NaN
                San Diego, CA La Jolla, CA Los Angeles, CA Santa Monica, CA
MSL_Trend_mm_yr           NaN          NaN             NaN              NaN
                Santa Barbara, CA Port San Luis, CA Monterey, CA
MSL_Trend_mm_yr               NaN               NaN          NaN
                San Francisco, CA Redwood City, CA Alameda, CA Richmond, CA
MSL_Trend_mm_yr               NaN              NaN         NaN          NaN
                Point Reyes, CA Port Chicago, CA Arena Cove, CA North Spit, CA
MSL_Trend_mm_yr             NaN              NaN            NaN            NaN
                Crescent City, CA Port Orford, OR Charleston, OR
MSL_Trend_mm_yr               NaN             NaN            NaN
                South Beach, OR Garibaldi, OR Astoria, OR Toke Point, WA
MSL_Trend_mm_yr             NaN           NaN         NaN            NaN
                Neah Bay, WA Port Angeles, WA Port Townsend, WA Seattle, WA
MSL_Trend_mm_yr          NaN              NaN               NaN         NaN
                Cherry Point, WA Friday Harbor, WA Ketchikan, AK Sitka, AK
MSL_Trend_mm_yr              NaN               NaN           NaN       NaN
                Juneau, AK Skagway, AK Yakutat, AK Cordova, AK Valdez, AK
MSL_Trend_mm_yr        NaN         NaN         NaN         NaN        NaN
                Seward, AK Seldovia, AK Nikiski, AK Anchorage, AK
MSL_Trend_mm_yr        NaN          NaN         NaN           NaN
                Kodiak Island, AK Sand Point, AK Adak Island, AK Unalaska, AK
MSL_Trend_mm_yr               NaN            NaN             NaN          NaN
                Port Moller, AK Nome, AK Prudhoe Bay, AK Lime Tree Bay, VI
MSL_Trend_mm_yr             NaN      NaN             NaN               NaN
                Charlotte Amalie, VI San Juan, PR Magueyes Island, PR
MSL_Trend_mm_yr                  NaN          NaN                 NaN
attr(,"scaled:center")
                  Nawiliwili, HI                     Honolulu, HI
                            1.90                             1.57
                    Mokuoloe, HI                      Kahului, HI
                            1.79                             2.30
                    Kawaihae, HI                         Hilo, HI
                            3.81                             3.15
                  Midway Atoll,               Apra Harbor, Guam,
                            1.58                             5.37
     Pago Pago, American Samoa,     Kwajalein, Marshall Islands,
                           15.48                             2.12
    Wake Island, Pacific Ocean,     Biological Station, Bermuda,
                            2.15                             2.21
          St. Georges, Bermuda,                      Eastport, ME
                            2.19                             2.33
                      Cutler, ME                   Bar Harbor, ME
                            2.34                             2.48
                    Portland, ME                Seavey Island, ME
                            1.97                             2.21
                  Fort Point, NH                       Boston, MA
                            2.04                             2.97
                  Woods Hole, MA             Nantucket Island, MA
                            3.15                             4.14
                     Newport, RI                   Providence, RI
                            2.98                             2.64
                  New London, CT                   Bridgeport, CT
                            2.94                             3.43
                     Montauk, NY                  Kings Point, NY
                            3.60                             2.74
                 The Battery, NY                 Bergen Point, NY
                            2.95                             4.72
                  Sandy Hook, NJ                Atlantic City, NJ
                            4.28                             4.25
                    Cape May, NJ                 Philadelphia, PA
                            5.10                             3.15
                 Reedy Point, DE                        Lewes, DE
                            3.94                             3.78
                  Ocean City, MD                    Cambridge, MD
                            5.25                             4.05
            Tolchester Beach, MD              Chesapeake City, MD
                            4.31                             4.47
                   Baltimore, MD                    Annapolis, MD
                            3.31                             3.87
             Solomons Island, MD                   Washington, DC
                            4.11                             3.54
                Wachapreague, VA                    Kiptopeke, VA
                            5.68                             4.02
                    Dahlgren, VA                    Lewisetta, VA
                            5.70                             5.93
              Windmill Point, VA                     Yorktown, VA
                            6.47                             4.84
               Sewells Point, VA Chesapeake Bay Bridge Tunnel, VA
                            4.84                             5.92
          Chesapeake Channel, VA                         Duck, NC
                            6.15                             4.94
         Oregon Inlet Marina, NC                     Beaufort, NC
                            5.50                             3.62
                  Wilmington, NC              Springmaid Pier, SC
                            2.80                             3.36
                  Charleston, SC                 Fort Pulaski, GA
                            3.51                             3.67
            Fernandina Beach, FL                      Mayport, FL
                            2.31                             2.92
              Port Canaveral, FL              Lake Worth Pier, FL
                            6.41                             4.12
                Virginia Key, FL                     Vaca Key, FL
                            3.20                             4.19
                    Key West, FL                       Naples, FL
                            2.64                             3.35
                  Fort Myers, FL                 Port Manatee, FL
                            3.62                             5.46
              St. Petersburg, FL               Old Port Tampa, FL
                            3.13                             6.04
                    East Bay, FL             Clearwater Beach, FL
                            5.50                             4.36
                   Cedar Key, FL                 Apalachicola, FL
                            2.39                             3.05
                 Panama City, FL            Panama City Beach, FL
                            3.08                             4.86
                   Pensacola, FL               Dauphin Island, AL
                            2.72                             4.37
          Mobile State Docks, AL                 Bay Waveland, MS
                            4.62                             4.59
                  Grand Isle, LA                    New Canal, LA
                            9.13                             5.99
                 Sabine Pass, TX                Morgans Point, TX
                            6.16                             3.80
                 Texas Point, TX                  Eagle Point, TX
                            5.76                            12.19
      Galveston Bay Entrance, TX            Galveston Pier 21, TX
                            6.59                             6.63
     Galveston Pleasure Pier, TX                     Freeport, TX
                            6.62                             4.21
             Freeport Harbor, TX                     Rockport, TX
                            3.51                             6.04
             Packery Channel, TX               Corpus Christi, TX
                            6.13                             5.48
              Port Mansfield, TX           South Padre Island, TX
                            3.73                             4.09
                 Port Isabel, TX                    San Diego, CA
                            4.35                             2.22
                    La Jolla, CA                  Los Angeles, CA
                            2.02                             1.07
                Santa Monica, CA                Santa Barbara, CA
                            1.52                             1.05
               Port San Luis, CA                     Monterey, CA
                            0.99                             1.77
               San Francisco, CA                 Redwood City, CA
                            1.99                             2.74
                     Alameda, CA                     Richmond, CA
                            0.94                             3.35
                 Point Reyes, CA                 Port Chicago, CA
                            2.15                             1.96
                  Arena Cove, CA                   North Spit, CA
                            1.15                             5.08
               Crescent City, CA                  Port Orford, OR
                           -0.76                            -0.05
                  Charleston, OR                  South Beach, OR
                            1.12                             1.75
                   Garibaldi, OR                      Astoria, OR
                            2.44                            -0.15
                  Toke Point, WA                     Neah Bay, WA
                            0.45                            -1.70
                Port Angeles, WA                Port Townsend, WA
                            0.46                             1.82
                     Seattle, WA                 Cherry Point, WA
                            2.09                            -0.04
               Friday Harbor, WA                    Ketchikan, AK
                            1.19                            -0.36
                       Sitka, AK                       Juneau, AK
                           -2.46                           -13.51
                     Skagway, AK                      Yakutat, AK
                          -18.13                           -15.40
                     Cordova, AK                       Valdez, AK
                           -0.54                            -8.77
                      Seward, AK                     Seldovia, AK
                           -3.08                            -9.51
                     Nikiski, AK                    Anchorage, AK
                          -10.12                            -0.69
               Kodiak Island, AK                   Sand Point, AK
                           -9.53                             2.04
                 Adak Island, AK                     Unalaska, AK
                           -2.30                            -4.18
                 Port Moller, AK                         Nome, AK
                            4.02                             4.15
                 Prudhoe Bay, AK                Lime Tree Bay, VI
                            4.28                             2.71
            Charlotte Amalie, VI                     San Juan, PR
                            2.21                             2.16
             Magueyes Island, PR
                            2.06
attr(,"scaled:scale")
                  Nawiliwili, HI                     Honolulu, HI
                               0                                0
                    Mokuoloe, HI                      Kahului, HI
                               0                                0
                    Kawaihae, HI                         Hilo, HI
                               0                                0
                  Midway Atoll,               Apra Harbor, Guam,
                               0                                0
     Pago Pago, American Samoa,     Kwajalein, Marshall Islands,
                               0                                0
    Wake Island, Pacific Ocean,     Biological Station, Bermuda,
                               0                                0
          St. Georges, Bermuda,                      Eastport, ME
                               0                                0
                      Cutler, ME                   Bar Harbor, ME
                               0                                0
                    Portland, ME                Seavey Island, ME
                               0                                0
                  Fort Point, NH                       Boston, MA
                               0                                0
                  Woods Hole, MA             Nantucket Island, MA
                               0                                0
                     Newport, RI                   Providence, RI
                               0                                0
                  New London, CT                   Bridgeport, CT
                               0                                0
                     Montauk, NY                  Kings Point, NY
                               0                                0
                 The Battery, NY                 Bergen Point, NY
                               0                                0
                  Sandy Hook, NJ                Atlantic City, NJ
                               0                                0
                    Cape May, NJ                 Philadelphia, PA
                               0                                0
                 Reedy Point, DE                        Lewes, DE
                               0                                0
                  Ocean City, MD                    Cambridge, MD
                               0                                0
            Tolchester Beach, MD              Chesapeake City, MD
                               0                                0
                   Baltimore, MD                    Annapolis, MD
                               0                                0
             Solomons Island, MD                   Washington, DC
                               0                                0
                Wachapreague, VA                    Kiptopeke, VA
                               0                                0
                    Dahlgren, VA                    Lewisetta, VA
                               0                                0
              Windmill Point, VA                     Yorktown, VA
                               0                                0
               Sewells Point, VA Chesapeake Bay Bridge Tunnel, VA
                               0                                0
          Chesapeake Channel, VA                         Duck, NC
                               0                                0
         Oregon Inlet Marina, NC                     Beaufort, NC
                               0                                0
                  Wilmington, NC              Springmaid Pier, SC
                               0                                0
                  Charleston, SC                 Fort Pulaski, GA