In [1]:
install.packages("nycflights13")
install.packages("tidyverse") #For dplyr

Installing package into 'C:/Users/sofoc/AppData/Local/R/win-library/4.5'
(as 'lib' is unspecified)

package 'nycflights13' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\sofoc\AppData\Local\Temp\Rtmp6xCel5\downloaded_packages

Installing package into 'C:/Users/sofoc/AppData/Local/R/win-library/4.5'
(as 'lib' is unspecified)

package 'tidyverse' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\sofoc\AppData\Local\Temp\Rtmp6xCel5\downloaded_packages

In [3]:
library(tidyverse)
library(nycflights13)

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [5]:
?flights

flights              package:nycflights13              R Documentation

_F_l_i_g_h_t_s _d_a_t_a

_D_e_s_c_r_i_p_t_i_o_n:

     On-time data for all flights that departed NYC (i.e. JFK, LGA or
     EWR) in 2013.

_U_s_a_g_e:

     flights

_F_o_r_m_a_t:

     Data frame with columns

     year, month, day Date of departure.

     dep_time, arr_time Actual departure and arrival times (format HHMM
          or HMM), local tz.

     sched_dep_time, sched_arr_time Scheduled departure and arrival
          times (format HHMM or HMM), local tz.

     dep_delay, arr_delay Departure and arrival delays, in minutes.
          Negative times represent early departures/arrivals.

     carrier Two letter carrier abbreviation. See 'airlines' to get
          name.

     flight Flight number.

     tailnum Plane tail number. See 'planes' for additional metadata.

     origin, dest Origin and destination. See 'airports' for additional
          metadata.

     air_time Amount of time spent in the air, in minutes.

     distance Distance between airports, in miles.

     hour, minute Time of scheduled departure broken into hour and
          minutes.

     time_hour Scheduled date and hour of the flight as a 'POSIXct'
          date. Along with 'origin', can be used to join flights data
          to 'weather' data.

_S_o_u_r_c_e:

     RITA, Bureau of transportation statistics,
     <https://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=236>

In [4]:
#In a single pipeline for each condition, find all flights that meet the condition:
glimpse(flights)

Rows: 336,776
Columns: 19
$ year           <int> 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2…
$ month          <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ day            <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ dep_time       <int> 517, 533, 542, 544, 554, 554, 555, 557, 557, 558, 558, …
$ sched_dep_time <int> 515, 529, 540, 545, 600, 558, 600, 600, 600, 600, 600, …
$ dep_delay      <dbl> 2, 4, 2, -1, -6, -4, -5, -3, -3, -2, -2, -2, -2, -2, -1…
$ arr_time       <int> 830, 850, 923, 1004, 812, 740, 913, 709, 838, 753, 849,…
$ sched_arr_time <int> 819, 830, 850, 1022, 837, 728, 854, 723, 846, 745, 851,…
$ arr_delay      <dbl> 11, 20, 33, -18, -25, 12, 19, -14, -8, 8, -2, -3, 7, -1…
$ carrier        <chr> "UA", "UA", "AA", "B6", "DL", "UA", "B6", "EV", "B6", "…
$ flight         <int> 1545, 1714, 1141, 725, 461, 1696, 507, 5708, 79, 301, 4…
$ tailnum        <chr> "N14228", "N24211", "N619AA", "N804JB", "N668DN", "N394…
$ origin         <chr> "EWR", "LGA", "JFK", "JFK", "LGA", "EWR", "EWR", "LGA",…
$ dest           <chr> "IAH", "IAH", "MIA", "BQN", "ATL", "ORD", "FLL", "IAD",…
$ air_time       <dbl> 227, 227, 160, 183, 116, 150, 158, 53, 140, 138, 149, 1…
$ distance       <dbl> 1400, 1416, 1089, 1576, 762, 719, 1065, 229, 944, 733, …
$ hour           <dbl> 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6…
$ minute         <dbl> 15, 29, 40, 45, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 0…
$ time_hour      <dttm> 2013-01-01 05:00:00, 2013-01-01 05:00:00, 2013-01-01 0…

In [11]:
flights |> #Flights firrst 
    filter(dep_delay >= 120) |> #then flights that have been delayed for more than 2 or more hours
    filter(dest %in% c("IAH", "HOU")) |> #then have flew to IAH or HOU
    filter(carrier %in% c("UA", "AA","DL")) |> #then operated by United, American, or Delta
    filter(month %in% c(7, 8, 9)) |> #%in% is used because you want to combine == AND | / #then departed in sumer
    filter(arr_delay >= 120 & dep_delay <= 0) |> #then arrived more than twoo hours late but didn't leave late
    filter(dep_delay == 60 & dep_delay - arr_delay > 30)

     year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
     arr_delay carrier flight tailnum origin dest air_time distance hour minute
     time_hour

In [12]:
flights |> #Flights first 
    filter(dep_delay >= 120)

     year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1    2013 1     1    848     1835           853       1001     1950
2    2013 1     1    957      733           144       1056      853
3    2013 1     1   1114      900           134       1447     1222
4    2013 1     1   1540     1338           122       2020     1825
5    2013 1     1   1815     1325           290       2120     1542
6    2013 1     1   1842     1422           260       1958     1535
7    2013 1     1   1856     1645           131       2212     2005
8    2013 1     1   1934     1725           129       2126     1855
9    2013 1     1   1938     1703           155       2109     1823
10   2013 1     1   1942     1705           157       2124     1830
11   2013 1     1   2006     1630           216       2230     1848
12   2013 1     1   2009     1808           121       2145     1942
13   2013 1     1   2115     1700           255       2330     1920
14   2013 1     1   2205     1720           285         46     2040
15   2013 1     1   2221     2000           141       2331     2124
16   2013 1     1   2312     2000           192         21     2110
17   2013 1     1   2343     1724           379        314     1938
18   2013 1     2    126     2250           156        233     2359
19   2013 1     2    833      558           155       1018      727
20   2013 1     2    923      624           179       1051      758
21   2013 1     2   1125      925           120       1445     1146
22   2013 1     2   1244      900           224       1431     1104
23   2013 1     2   1332      904           268       1616     1128
24   2013 1     2   1412      838           334       1710     1147
25   2013 1     2   1451     1232           139       1749     1533
26   2013 1     2   1548     1340           128       1710     1500
27   2013 1     2   1607     1030           337       2003     1355
28   2013 1     2   1728     1515           133       1843     1632
29   2013 1     2   1751     1450           181       2041     1755
30   2013 1     2   1755     1547           128       1929     1708
⋮    ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
9859 2013 9     27   928      600           208       1106      754
9860 2013 9     27  1106      840           146       1243     1023
9861 2013 9     27  1108      840           148       1213     1005
9862 2013 9     27  1648     1436           132       1810     1559
9863 2013 9     27  1713     1350           203       1838     1531
9864 2013 9     27  1809     1515           174       2026     1724
9865 2013 9     27  2057     1842           135       2203     2019
9866 2013 9     27  2253     1945           188         NA     2146
9867 2013 9     28  1253      910           223       1422     1112
9868 2013 9     28  1458     1240           138       1633     1438
9869 2013 9     28  2017     1455           322       2154     1630
9870 2013 9     29  1435     1226           129       1552     1338
9871 2013 9     29  1615     1355           140       1759     1542
9872 2013 9     29  1639     1329           190       1857     1529
9873 2013 9     29  1709     1500           129       1939     1804
9874 2013 9     29  1745     1330           255       2028     1632
9875 2013 9     29  2049     1730           199       2153     1852
9876 2013 9     29  2245     2034           131         27     2237
9877 2013 9     29  2253     2000           173        121     2300
9878 2013 9     29  2324     2100           144         39     2235
9879 2013 9     29  2327     1942           225        153     2250
9880 2013 9     30   827      615           132       1022      811
9881 2013 9     30  1240     1015           145       1421     1212
9882 2013 9     30  1324      830           294       1512     1040
9883 2013 9     30  1738     1529           129       1906     1649
9884 2013 9     30  1823     1545           158       1934     1733
9885 2013 9     30  1951     1649           182       2157     1903
9886 2013 9     30  2053     1815           158       2310     2054
9887 2013 9     30  2159     1845           194       2344     2030
9888 2013 9     30  2235     2001           154         59     2249
     arr_delay carrier flight tailnum origin dest air_time distance hour minute
1    851       MQ      3944   N942MQ  JFK    BWI   41       184     18   35
2    123       UA       856   N534UA  EWR    BOS   37       200      7   33
3    145       UA      1086   N76502  LGA    IAH  248      1416      9    0
4    115       B6       705   N570JB  JFK    SJU  193      1598     13   38
5    338       EV      4417   N17185  EWR    OMA  213      1134     13   25
6    263       EV      4633   N18120  EWR    BTV   46       266     14   22
7    127       AA       181   N323AA  JFK    LAX  336      2475     16   45
8    151       MQ      4255   N909MQ  JFK    BNA  154       765     17   25
9    166       EV      4300   N18557  EWR    RIC   68       277     17    3
10   174       MQ      4410   N835MQ  JFK    DCA   60       213     17    5
11   222       EV      4644   N14972  EWR    SAV  121       708     16   30
12   123       EV      4440   N14143  EWR    PIT   65       319     18    8
13   250       9E      3347   N924XJ  JFK    CVG  115       589     17    0
14   246       AA      1999   N5DNAA  EWR    MIA  146      1085     17   20
15   127       EV      4462   N13566  EWR    BUF   56       282     20    0
16   191       EV      4312   N13958  EWR    DCA   44       199     20    0
17   456       EV      4321   N21197  EWR    MCI  222      1092     17   24
18   154       B6        22   N636JB  JFK    SYR   49       209     22   50
19   171       UA       651   N448UA  EWR    ORD  129       719      5   58
20   173       EV      4104   N13975  EWR    PIT   61       319      6   24
21    NA       9E      3658   N8783E  LGA    GRR   NA       618      9   25
22   207       EV      4412   N13958  EWR    MYR   94       550      9    0
23   288       EV      4364   N41104  EWR    MCI  203      1092      9    4
24   323       UA       468   N474UA  EWR    MCO  150       937      8   38
25   136       UA      1121   N33284  EWR    FLL  158      1065     12   32
26   130       EV      4617   N10575  EWR    PIT   63       319     13   40
27   368       AA       179   N324AA  JFK    SFO  346      2586     10   30
28   131       EV      4133   N13975  EWR    IAD   48       212     15   15
29   166       AA      1813   N5FFAA  JFK    MCO  149       944     14   50
30   141       EV      3272   N21130  EWR    BUF   51       282     15   47
⋮    ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮    ⋮
9859 192       EV      5068   N752EV  EWR    DTW   70       488      6    0
9860 140       EV      4941   N398CA  LGA    ORF   46       296      8   40
9861 128       EV      5813   N13958  EWR    RIC   51       277      8   40
9862 131       EV      5713   N830AS  LGA    IAD   46       229     14   36
9863 187       EV      5465   N398CA  LGA    MSN  111       812     13   50
9864 182       EV      4181   N27200  EWR    MCI  149      1092     15   15
9865 104       EV      5274   N720EV  LGA    BNA   98       764     18   42
9866  NA       EV      5306   N605QX  LGA    GSO   NA       461     19   45
9867 190       EV      5222   N759EV  EWR    DTW   74       488      9   10
9868 115       EV      5067   N137EV  EWR    DTW   71       488     12   40
9869 324       MQ      3231   N812MQ  JFK    PIT   66       340     14   55
9870 134       UA       252   N431UA  EWR    BOS   33       200     12   26
9871 137       EV      4100   N11193  EWR    MEM  133       946     13   55
9872 208       MQ      3340   N812MQ  LGA    DTW   92       502     13   29
9873  95       DL      1935   N316NB  LGA    TPA  126      1010     15    0
9874 236       B6       431   N517JB  LGA    SRQ  137      1047     13   30
9875 181       B6        86   N373JB  JFK    ROC   44       264     17   30
9876 110       EV      4348   N11193  EWR    MSP  141      1008     20   34
9877 141       VX       415   N628VA  JFK    LAX  303      2475     20    0
9878 124       MQ      3317   N528MQ  LGA    RDU   61       431     21    0
9879 183       B6      1271   N659JB  LGA    FLL  129      1076     19   42
9880 131       US      1772   N556UW  JFK    CLT   91       541      6   15
9881 129       US      2067   N102UW  JFK    CLT   76       541     10   15
9882 272       EV      5157   N761ND  LGA    CLT   79       544      8   30
9883 137       EV      4580   N12563  EWR    MKE  110       725     15   29
9884 121       9E      3459   N916XJ  JFK    BNA   95       765     15   45
9885 174       EV      4294   N13988  EWR    SAV   95       708     16   49
9886 136       EV      5292   N600QX  EWR    ATL   91       746     18   15
9887 194       9E      3320   N906XJ  JFK    BUF   50       301     18   45
9888 130       B6      1083   N804JB  JFK    MCO  123       944     20    1
     time_hour
1    2013-01-01 18:00:00
2    2013-01-01 07:00:00
3    2013-01-01 09:00:00
4    2013-01-01 13:00:00
5    2013-01-01 13:00:00
6    2013-01-01 14:00:00
7    2013-01-01 16:00:00
8    2013-01-01 17:00:00
9    2013-01-01 17:00:00
10   2013-01-01 17:00:00
11   2013-01-01 16:00:00
12   2013-01-01 18:00:00
13   2013-01-01 17:00:00
14   2013-01-01 17:00:00
15   2013-01-01 20:00:00
16   2013-01-01 20:00:00
17   2013-01-01 17:00:00
18   2013-01-02 22:00:00
19   2013-01-02 05:00:00
20   2013-01-02 06:00:00
21   2013-01-02 09:00:00
22   2013-01-02 09:00:00
23   2013-01-02 09:00:00
24   2013-01-02 08:00:00
25   2013-01-02 12:00:00
26   2013-01-02 13:00:00
27   2013-01-02 10:00:00
28   2013-01-02 15:00:00
29   2013-01-02 14:00:00
30   2013-01-02 15:00:00
⋮    ⋮
9859 2013-09-27 06:00:00
9860 2013-09-27 08:00:00
9861 2013-09-27 08:00:00
9862 2013-09-27 14:00:00
9863 2013-09-27 13:00:00
9864 2013-09-27 15:00:00
9865 2013-09-27 18:00:00
9866 2013-09-27 19:00:00
9867 2013-09-28 09:00:00
9868 2013-09-28 12:00:00
9869 2013-09-28 14:00:00
9870 2013-09-29 12:00:00
9871 2013-09-29 13:00:00
9872 2013-09-29 13:00:00
9873 2013-09-29 15:00:00
9874 2013-09-29 13:00:00
9875 2013-09-29 17:00:00
9876 2013-09-29 20:00:00
9877 2013-09-29 20:00:00
9878 2013-09-29 21:00:00
9879 2013-09-29 19:00:00
9880 2013-09-30 06:00:00
9881 2013-09-30 10:00:00
9882 2013-09-30 08:00:00
9883 2013-09-30 15:00:00
9884 2013-09-30 15:00:00
9885 2013-09-30 16:00:00
9886 2013-09-30 18:00:00
9887 2013-09-30 18:00:00
9888 2013-09-30 20:00:00

In [15]:
flights |> arrange(desc(dep_delay))  #Longest departure delays

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013  1     9   641      900           1301      1242     1530
2      2013  6    15  1432     1935           1137      1607     2120
3      2013  1    10  1121     1635           1126      1239     1810
4      2013  9    20  1139     1845           1014      1457     2210
5      2013  7    22   845     1600           1005      1044     1815
6      2013  4    10  1100     1900            960      1342     2211
7      2013  3    17  2321      810            911       135     1020
8      2013  6    27   959     1900            899      1236     2226
9      2013  7    22  2257      759            898       121     1026
10     2013 12     5   756     1700            896      1058     2020
11     2013  5     3  1133     2055            878      1250     2215
12     2013  1     1   848     1835            853      1001     1950
13     2013  2    10  2243      830            853       100     1106
14     2013  5    19   713     1700            853      1007     1955
15     2013 12    19   734     1725            849      1046     2039
16     2013 12    17   705     1700            845      1026     2020
17     2013 12    14   830     1845            825      1210     2154
18     2013  4    19   912     1940            812      1228     2247
19     2013  6    27   753     1830            803       937     2015
20     2013  3    18  1020     2100            800      1336       32
21     2013 11     3   603     1645            798       829     1913
22     2013  4    19   617     1700            797       858     1955
23     2013  6    27   615     1705            790       853     2004
24     2013  2    19  2324     1016            788       114     1227
25     2013  6    27   732     1825            787       932     2032
26     2013  2    24  1921      615            786      2135      842
27     2013  4    19   606     1725            761       923     2020
28     2013  4    19   758     1925            753      1049     2225
29     2013  2    16   757     1930            747      1013     2149
30     2013 10    14  2042      900            702      2255     1127
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336747 2013 9     24  NA       1625           NA        NA       1750
336748 2013 9     25  NA       1259           NA        NA       1507
336749 2013 9     25  NA        845           NA        NA       1018
336750 2013 9     25  NA       1755           NA        NA       1932
336751 2013 9     25  NA        600           NA        NA        716
336752 2013 9     25  NA        836           NA        NA        944
336753 2013 9     25  NA       1300           NA        NA       1409
336754 2013 9     25  NA       1900           NA        NA       2014
336755 2013 9     25  NA       1300           NA        NA       1450
336756 2013 9     25  NA       1655           NA        NA       1840
336757 2013 9     25  NA       1559           NA        NA       1719
336758 2013 9     26  NA        915           NA        NA       1141
336759 2013 9     26  NA       1400           NA        NA       1512
336760 2013 9     26  NA       1240           NA        NA       1525
336761 2013 9     27  NA        600           NA        NA        730
336762 2013 9     27  NA       2100           NA        NA       2211
336763 2013 9     27  NA       1329           NA        NA       1444
336764 2013 9     27  NA       1600           NA        NA       1739
336765 2013 9     28  NA       1803           NA        NA       1927
336766 2013 9     28  NA        910           NA        NA       1220
336767 2013 9     28  NA       1635           NA        NA       1827
336768 2013 9     29  NA       2054           NA        NA       2302
336769 2013 9     29  NA       1830           NA        NA       2010
336770 2013 9     29  NA        700           NA        NA        833
336771 2013 9     30  NA       1842           NA        NA       2019
336772 2013 9     30  NA       1455           NA        NA       1634
336773 2013 9     30  NA       2200           NA        NA       2312
336774 2013 9     30  NA       1210           NA        NA       1330
336775 2013 9     30  NA       1159           NA        NA       1344
336776 2013 9     30  NA        840           NA        NA       1020
       arr_delay carrier flight tailnum origin dest air_time distance hour
1      1272      HA        51   N384HA  JFK    HNL  640      4983      9
2      1127      MQ      3535   N504MQ  JFK    CMH   74       483     19
3      1109      MQ      3695   N517MQ  EWR    ORD  111       719     16
4      1007      AA       177   N338AA  JFK    SFO  354      2586     18
5       989      MQ      3075   N665MQ  JFK    CVG   96       589     16
6       931      DL      2391   N959DL  JFK    TPA  139      1005     19
7       915      DL      2119   N927DA  LGA    MSP  167      1020      8
8       850      DL      2007   N3762Y  JFK    PDX  313      2454     19
9       895      DL      2047   N6716C  LGA    ATL  109       762      7
10      878      AA       172   N5DMAA  EWR    MIA  149      1085     17
11      875      MQ      3744   N523MQ  EWR    ORD  112       719     20
12      851      MQ      3944   N942MQ  JFK    BWI   41       184     18
13      834      F9       835   N203FR  LGA    DEN  233      1620      8
14      852      AA       257   N3HEAA  JFK    LAS  323      2248     17
15      847      DL      1223   N375NC  EWR    SLC  290      1969     17
16      846      AA       172   N5EMAA  EWR    MIA  145      1085     17
17      856      DL      2391   N939DL  JFK    TPA  173      1005     18
18      821      DL      1435   N900DE  LGA    TPA  174      1010     19
19      802      AA      2019   N571AA  LGA    STL  134       888     18
20      784      DL      2363   N624AG  JFK    LAX  335      2475     21
21      796      DL      2042   N990AT  EWR    ATL  109       746     16
22      783      AA       257   N3GJAA  JFK    LAS  313      2248     17
23      769      DL       503   N372DA  JFK    SAN  312      2446     17
24      767      DL      2319   N324US  LGA    MSP  136      1020     10
25      780      DL      1715   N335NB  LGA    MSY  160      1183     18
26      773      DL       575   N348NW  EWR    ATL  111       746      6
27      783      AA      1901   N3DGAA  JFK    IAH  222      1417     17
28      744      DL      1485   N927DA  LGA    MCO  149       950     19
29      744      9E      3798   N8940E  JFK    CLT   85       541     19
30      688      DL       502   N943DL  EWR    ATL   98       746      9
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
336747 NA        MQ      3622   N524MQ  LGA    BNA  NA        764     16
336748 NA        EV      5207   N615QX  LGA    CLT  NA        544     12
336749 NA        EV      5286   N615QX  LGA    BTV  NA        258      8
336750 NA        EV      5287   N722EV  LGA    MSN  NA        812     17
336751 NA        EV      5716   N877AS  JFK    IAD  NA        228      6
336752 NA        B6      2280   N258JB  EWR    BOS  NA        200      8
336753 NA        US      2148   NA      LGA    BOS  NA        184     13
336754 NA        US      2160   NA      LGA    BOS  NA        184     19
336755 NA        MQ      3388   N817MQ  LGA    CMH  NA        479     13
336756 NA        MQ      3411   N735MQ  LGA    RDU  NA        431     16
336757 NA        MQ      3748   N530MQ  EWR    ORD  NA        719     15
336758 NA        EV      5109   N748EV  LGA    CHS  NA        641      9
336759 NA        US      2183   NA      LGA    DCA  NA        214     14
336760 NA        WN      4720   N691WN  EWR    HOU  NA       1411     12
336761 NA        AA       301   N584AA  LGA    ORD  NA        733      6
336762 NA        US      2164   NA      LGA    BOS  NA        184     21
336763 NA        MQ      3760   N505MQ  EWR    ORD  NA        719     13
336764 NA        UA       269   NA      LGA    ORD  NA        733     16
336765 NA        EV      5563   N724EV  LGA    BTV  NA        258     18
336766 NA        AA         1   N320AA  JFK    LAX  NA       2475      9
336767 NA        US       581   NA      EWR    CLT  NA        529     16
336768 NA        EV      4536   N13988  EWR    CVG  NA        569     20
336769 NA        MQ      3134   N508MQ  EWR    ORD  NA        719     18
336770 NA        UA       331   NA      LGA    ORD  NA        733      7
336771 NA        EV      5274   N740EV  LGA    BNA  NA        764     18
336772 NA        9E      3393   NA      JFK    DCA  NA        213     14
336773 NA        9E      3525   NA      LGA    SYR  NA        198     22
336774 NA        MQ      3461   N535MQ  LGA    BNA  NA        764     12
336775 NA        MQ      3572   N511MQ  LGA    CLE  NA        419     11
336776 NA        MQ      3531   N839MQ  LGA    RDU  NA        431      8
       minute time_hour
1       0     2013-01-09 09:00:00
2      35     2013-06-15 19:00:00
3      35     2013-01-10 16:00:00
4      45     2013-09-20 18:00:00
5       0     2013-07-22 16:00:00
6       0     2013-04-10 19:00:00
7      10     2013-03-17 08:00:00
8       0     2013-06-27 19:00:00
9      59     2013-07-22 07:00:00
10      0     2013-12-05 17:00:00
11     55     2013-05-03 20:00:00
12     35     2013-01-01 18:00:00
13     30     2013-02-10 08:00:00
14      0     2013-05-19 17:00:00
15     25     2013-12-19 17:00:00
16      0     2013-12-17 17:00:00
17     45     2013-12-14 18:00:00
18     40     2013-04-19 19:00:00
19     30     2013-06-27 18:00:00
20      0     2013-03-18 21:00:00
21     45     2013-11-03 16:00:00
22      0     2013-04-19 17:00:00
23      5     2013-06-27 17:00:00
24     16     2013-02-19 10:00:00
25     25     2013-06-27 18:00:00
26     15     2013-02-24 06:00:00
27     25     2013-04-19 17:00:00
28     25     2013-04-19 19:00:00
29     30     2013-02-16 19:00:00
30      0     2013-10-14 09:00:00
⋮      ⋮      ⋮
336747 25     2013-09-24 16:00:00
336748 59     2013-09-25 12:00:00
336749 45     2013-09-25 08:00:00
336750 55     2013-09-25 17:00:00
336751  0     2013-09-25 06:00:00
336752 36     2013-09-25 08:00:00
336753  0     2013-09-25 13:00:00
336754  0     2013-09-25 19:00:00
336755  0     2013-09-25 13:00:00
336756 55     2013-09-25 16:00:00
336757 59     2013-09-25 15:00:00
336758 15     2013-09-26 09:00:00
336759  0     2013-09-26 14:00:00
336760 40     2013-09-26 12:00:00
336761  0     2013-09-27 06:00:00
336762  0     2013-09-27 21:00:00
336763 29     2013-09-27 13:00:00
336764  0     2013-09-27 16:00:00
336765  3     2013-09-28 18:00:00
336766 10     2013-09-28 09:00:00
336767 35     2013-09-28 16:00:00
336768 54     2013-09-29 20:00:00
336769 30     2013-09-29 18:00:00
336770  0     2013-09-29 07:00:00
336771 42     2013-09-30 18:00:00
336772 55     2013-09-30 14:00:00
336773  0     2013-09-30 22:00:00
336774 10     2013-09-30 12:00:00
336775 59     2013-09-30 11:00:00
336776 40     2013-09-30 08:00:00

In [17]:
flights |> arrange(dep_delay) #Earliest departures in the morning

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 12     7  2040     2123           -43         40     2352
2      2013  2     3  2022     2055           -33       2240     2338
3      2013 11    10  1408     1440           -32       1549     1559
4      2013  1    11  1900     1930           -30       2233     2243
5      2013  1    29  1703     1730           -27       1947     1957
6      2013  8     9   729      755           -26       1002      955
7      2013 10    23  1907     1932           -25       2143     2143
8      2013  3    30  2030     2055           -25       2213     2250
9      2013  3     2  1431     1455           -24       1601     1631
10     2013  5     5   934      958           -24       1225     1309
11     2013  5    14   914      938           -24       1143     1204
12     2013  9    18  1631     1655           -24       1812     1845
13     2013 10    29  2043     2106           -23       2145     2213
14     2013 11    18  2006     2029           -23       2134     2216
15     2013 12    25  2036     2059           -23       2313     2314
16     2013  5    18  1912     1935           -23       2126     2119
17     2013  9     1  1342     1405           -23       1448     1516
18     2013  9    14  2114     2137           -23       2351       27
19     2013  1    12  1354     1416           -22       1606     1650
20     2013  1    21  2137     2159           -22       2232     2316
21     2013 10    30  1037     1059           -22       1321     1405
22     2013 11    12  2044     2106           -22       2143     2213
23     2013  2     6  1528     1550           -22       1750     1826
24     2013  3    16  1147     1209           -22       1249     1322
25     2013  5    14   903      925           -22       1100     1110
26     2013  7    29  1933     1955           -22       2113     2145
27     2013  9     1  1748     1810           -22       1914     1955
28     2013  9    14  2223     2245           -22       2327     2351
29     2013  9    18   743      805           -22       1021     1101
30     2013  1    20   704      725           -21       1025     1035
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336747 2013 9     24  NA       1625           NA        NA       1750
336748 2013 9     25  NA       1259           NA        NA       1507
336749 2013 9     25  NA        845           NA        NA       1018
336750 2013 9     25  NA       1755           NA        NA       1932
336751 2013 9     25  NA        600           NA        NA        716
336752 2013 9     25  NA        836           NA        NA        944
336753 2013 9     25  NA       1300           NA        NA       1409
336754 2013 9     25  NA       1900           NA        NA       2014
336755 2013 9     25  NA       1300           NA        NA       1450
336756 2013 9     25  NA       1655           NA        NA       1840
336757 2013 9     25  NA       1559           NA        NA       1719
336758 2013 9     26  NA        915           NA        NA       1141
336759 2013 9     26  NA       1400           NA        NA       1512
336760 2013 9     26  NA       1240           NA        NA       1525
336761 2013 9     27  NA        600           NA        NA        730
336762 2013 9     27  NA       2100           NA        NA       2211
336763 2013 9     27  NA       1329           NA        NA       1444
336764 2013 9     27  NA       1600           NA        NA       1739
336765 2013 9     28  NA       1803           NA        NA       1927
336766 2013 9     28  NA        910           NA        NA       1220
336767 2013 9     28  NA       1635           NA        NA       1827
336768 2013 9     29  NA       2054           NA        NA       2302
336769 2013 9     29  NA       1830           NA        NA       2010
336770 2013 9     29  NA        700           NA        NA        833
336771 2013 9     30  NA       1842           NA        NA       2019
336772 2013 9     30  NA       1455           NA        NA       1634
336773 2013 9     30  NA       2200           NA        NA       2312
336774 2013 9     30  NA       1210           NA        NA       1330
336775 2013 9     30  NA       1159           NA        NA       1344
336776 2013 9     30  NA        840           NA        NA       1020
       arr_delay carrier flight tailnum origin dest air_time distance hour
1       48       B6        97   N592JB  JFK    DEN  265      1626     21
2      -58       DL      1715   N612DL  LGA    MSY  162      1183     20
3      -10       EV      5713   N825AS  LGA    IAD   52       229     14
4      -10       DL      1435   N934DL  LGA    TPA  139      1010     19
5      -10       F9       837   N208FR  LGA    DEN  250      1620     17
6        7       MQ      3478   N711MQ  LGA    DTW   88       502      7
7        0       EV      4361   N13994  EWR    TYS  111       631     19
8      -37       MQ      4573   N725MQ  LGA    DTW   87       502     20
9      -30       9E      3318   N929XJ  JFK    BUF   55       301     14
10     -44       B6       375   N531JB  LGA    FLL  150      1076      9
11     -21       9E      4065   N8747B  LGA    SDF  107       659      9
12     -33       AA      2223   N4XXAA  LGA    STL  125       888     16
13     -28       B6      2680   N190JB  EWR    BOS   43       200     21
14     -42       EV      5956   N29906  LGA    CLE   69       419     20
15      -1       MQ      3473   N512MQ  LGA    ATL  120       762     20
16       7       9E      4127   N800AY  JFK    IAD   45       228     19
17     -28       B6      2480   N279JB  EWR    BOS   47       200     14
18     -36       B6      1371   N517JB  LGA    FLL  135      1076     21
19     -44       FL       349   N929AT  LGA    ATL  110       762     14
20     -44       DL      2155   N377NW  LGA    PWM   38       269     21
21     -44       B6       971   N570JB  LGA    FLL  136      1076     10
22     -30       B6      2680   N317JB  EWR    BOS   40       200     21
23     -36       9E      3427   N923XJ  JFK    IND  109       665     15
24     -33       EV      3267   N13903  EWR    BTV   49       266     12
25     -10       AA      1855   N4WPAA  LGA    STL  126       888      9
26     -32       MQ      3573   N717MQ  LGA    CMH   70       479     19
27     -41       MQ      3526   N521MQ  LGA    CMH   69       479     18
28     -24       B6      1816   N274JB  JFK    SYR   41       209     22
29     -40       DL      1109   N337NB  LGA    TPA  141      1010      8
30     -10       AS        11   N556AS  EWR    SEA  348      2402      7
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
336747 NA        MQ      3622   N524MQ  LGA    BNA  NA        764     16
336748 NA        EV      5207   N615QX  LGA    CLT  NA        544     12
336749 NA        EV      5286   N615QX  LGA    BTV  NA        258      8
336750 NA        EV      5287   N722EV  LGA    MSN  NA        812     17
336751 NA        EV      5716   N877AS  JFK    IAD  NA        228      6
336752 NA        B6      2280   N258JB  EWR    BOS  NA        200      8
336753 NA        US      2148   NA      LGA    BOS  NA        184     13
336754 NA        US      2160   NA      LGA    BOS  NA        184     19
336755 NA        MQ      3388   N817MQ  LGA    CMH  NA        479     13
336756 NA        MQ      3411   N735MQ  LGA    RDU  NA        431     16
336757 NA        MQ      3748   N530MQ  EWR    ORD  NA        719     15
336758 NA        EV      5109   N748EV  LGA    CHS  NA        641      9
336759 NA        US      2183   NA      LGA    DCA  NA        214     14
336760 NA        WN      4720   N691WN  EWR    HOU  NA       1411     12
336761 NA        AA       301   N584AA  LGA    ORD  NA        733      6
336762 NA        US      2164   NA      LGA    BOS  NA        184     21
336763 NA        MQ      3760   N505MQ  EWR    ORD  NA        719     13
336764 NA        UA       269   NA      LGA    ORD  NA        733     16
336765 NA        EV      5563   N724EV  LGA    BTV  NA        258     18
336766 NA        AA         1   N320AA  JFK    LAX  NA       2475      9
336767 NA        US       581   NA      EWR    CLT  NA        529     16
336768 NA        EV      4536   N13988  EWR    CVG  NA        569     20
336769 NA        MQ      3134   N508MQ  EWR    ORD  NA        719     18
336770 NA        UA       331   NA      LGA    ORD  NA        733      7
336771 NA        EV      5274   N740EV  LGA    BNA  NA        764     18
336772 NA        9E      3393   NA      JFK    DCA  NA        213     14
336773 NA        9E      3525   NA      LGA    SYR  NA        198     22
336774 NA        MQ      3461   N535MQ  LGA    BNA  NA        764     12
336775 NA        MQ      3572   N511MQ  LGA    CLE  NA        419     11
336776 NA        MQ      3531   N839MQ  LGA    RDU  NA        431      8
       minute time_hour
1      23     2013-12-07 21:00:00
2      55     2013-02-03 20:00:00
3      40     2013-11-10 14:00:00
4      30     2013-01-11 19:00:00
5      30     2013-01-29 17:00:00
6      55     2013-08-09 07:00:00
7      32     2013-10-23 19:00:00
8      55     2013-03-30 20:00:00
9      55     2013-03-02 14:00:00
10     58     2013-05-05 09:00:00
11     38     2013-05-14 09:00:00
12     55     2013-09-18 16:00:00
13      6     2013-10-29 21:00:00
14     29     2013-11-18 20:00:00
15     59     2013-12-25 20:00:00
16     35     2013-05-18 19:00:00
17      5     2013-09-01 14:00:00
18     37     2013-09-14 21:00:00
19     16     2013-01-12 14:00:00
20     59     2013-01-21 21:00:00
21     59     2013-10-30 10:00:00
22      6     2013-11-12 21:00:00
23     50     2013-02-06 15:00:00
24      9     2013-03-16 12:00:00
25     25     2013-05-14 09:00:00
26     55     2013-07-29 19:00:00
27     10     2013-09-01 18:00:00
28     45     2013-09-14 22:00:00
29      5     2013-09-18 08:00:00
30     25     2013-01-20 07:00:00
⋮      ⋮      ⋮
336747 25     2013-09-24 16:00:00
336748 59     2013-09-25 12:00:00
336749 45     2013-09-25 08:00:00
336750 55     2013-09-25 17:00:00
336751  0     2013-09-25 06:00:00
336752 36     2013-09-25 08:00:00
336753  0     2013-09-25 13:00:00
336754  0     2013-09-25 19:00:00
336755  0     2013-09-25 13:00:00
336756 55     2013-09-25 16:00:00
336757 59     2013-09-25 15:00:00
336758 15     2013-09-26 09:00:00
336759  0     2013-09-26 14:00:00
336760 40     2013-09-26 12:00:00
336761  0     2013-09-27 06:00:00
336762  0     2013-09-27 21:00:00
336763 29     2013-09-27 13:00:00
336764  0     2013-09-27 16:00:00
336765  3     2013-09-28 18:00:00
336766 10     2013-09-28 09:00:00
336767 35     2013-09-28 16:00:00
336768 54     2013-09-29 20:00:00
336769 30     2013-09-29 18:00:00
336770  0     2013-09-29 07:00:00
336771 42     2013-09-30 18:00:00
336772 55     2013-09-30 14:00:00
336773  0     2013-09-30 22:00:00
336774 10     2013-09-30 12:00:00
336775 59     2013-09-30 11:00:00
336776 40     2013-09-30 08:00:00

In [18]:
flights |> arrange(distance)

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013 7     27    NA      106            NA         NA      245
2      2013 1      3  2127     2129            -2       2222     2224
3      2013 1      4  1240     1200            40       1333     1306
4      2013 1      4  1829     1615           134       1937     1721
5      2013 1      4  2128     2129            -1       2218     2224
6      2013 1      5  1155     1200            -5       1241     1306
7      2013 1      6  2125     2129            -4       2224     2224
8      2013 1      7  2124     2129            -5       2212     2224
9      2013 1      8  2127     2130            -3       2304     2225
10     2013 1      9  2126     2129            -3       2217     2224
11     2013 1     10  2133     2129             4       2223     2224
12     2013 1     11  2135     2129             6       2233     2224
13     2013 1     12  1613     1617            -4       1708     1722
14     2013 1     13  2243     2129            74       2400     2224
15     2013 1     14  2128     2129            -1       2215     2224
16     2013 1     15  2122     2130            -8       2207     2225
17     2013 1     16  2125     2129            -4       2214     2224
18     2013 1     17  2318     2129           109       2358     2224
19     2013 1     18  2231     2129            62       2320     2224
20     2013 1     19  1617     1617             0       1722     1722
21     2013 1     20  2219     2129            50       2316     2224
22     2013 1     21  2123     2129            -6       2216     2224
23     2013 1     22  2203     2130            33       2317     2225
24     2013 1     23  2128     2129            -1       2221     2224
25     2013 1     24  2241     2129            72       2350     2224
26     2013 1     25  2305     2129            96       2357     2224
27     2013 1     26  1621     1617             4       1705     1722
28     2013 1     27  2128     2129            -1       2213     2224
29     2013 1     28  2201     2129            32       2259     2224
30     2013 1     29  2131     2130             1       2221     2225
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336747 2013 8     27  1000     1000             0       1419     1440
336748 2013 8     28   957     1000            -3       1438     1440
336749 2013 8     29   955     1000            -5       1431     1440
336750 2013 8     30   954     1000            -6       1428     1440
336751 2013 8     31   958     1000            -2       1448     1440
336752 2013 9      1   953     1000            -7       1423     1445
336753 2013 9      2   956     1000            -4       1425     1445
336754 2013 9      3   955     1000            -5       1418     1445
336755 2013 9      4   945     1000           -15       1401     1445
336756 2013 9      5   950     1000           -10       1424     1445
336757 2013 9      6   955     1000            -5       1359     1445
336758 2013 9      7   953     1000            -7       1407     1445
336759 2013 9      8   959     1000            -1       1413     1445
336760 2013 9      9   958     1000            -2       1427     1445
336761 2013 9     10   945     1000           -15       1402     1445
336762 2013 9     11   955     1000            -5       1419     1445
336763 2013 9     13   953     1000            -7       1416     1445
336764 2013 9     14   955     1000            -5       1417     1445
336765 2013 9     15  1002     1000             2       1442     1445
336766 2013 9     16   957     1000            -3       1452     1445
336767 2013 9     18   953     1000            -7       1447     1445
336768 2013 9     20   956     1000            -4       1441     1445
336769 2013 9     21   954     1000            -6       1426     1445
336770 2013 9     22   952     1000            -8       1439     1445
336771 2013 9     23   955     1000            -5       1437     1445
336772 2013 9     25  1001     1000             1       1508     1445
336773 2013 9     27   951     1000            -9       1442     1445
336774 2013 9     28   955     1000            -5       1412     1445
336775 2013 9     29   957     1000            -3       1405     1445
336776 2013 9     30   959     1000            -1       1438     1445
       arr_delay carrier flight tailnum origin dest air_time distance hour
1       NA       US      1632   NA      EWR    LGA  NA       17        1
2       -2       EV      3833   N13989  EWR    PHL  30       80       21
3       27       EV      4193   N14972  EWR    PHL  30       80       12
4      136       EV      4502   N15983  EWR    PHL  28       80       16
5       -6       EV      4645   N27962  EWR    PHL  32       80       21
6      -25       EV      4193   N14902  EWR    PHL  29       80       12
7        0       EV      4619   N22909  EWR    PHL  22       80       21
8      -12       EV      4619   N33182  EWR    PHL  25       80       21
9       39       EV      4619   N11194  EWR    PHL  30       80       21
10      -7       EV      4619   N17560  EWR    PHL  27       80       21
11      -1       EV      3271   N12569  EWR    PHL  30       80       21
12       9       EV      4619   N15980  EWR    PHL  30       80       21
13     -14       EV      4616   N11150  EWR    PHL  36       80       16
14      96       EV      4619   N16963  EWR    PHL  31       80       21
15      -9       EV      4619   N14953  EWR    PHL  25       80       21
16     -18       EV      4619   N16976  EWR    PHL  26       80       21
17     -10       EV      4619   N14993  EWR    PHL  31       80       21
18      94       EV      3271   N11535  EWR    PHL  28       80       21
19      56       EV      4619   N14916  EWR    PHL  31       80       21
20       0       EV      4616   N12540  EWR    PHL  34       80       16
21      52       EV      4619   N15574  EWR    PHL  30       80       21
22      -8       EV      4619   N19554  EWR    PHL  32       80       21
23      52       EV      4619   N13538  EWR    PHL  31       80       21
24      -3       EV      4619   N12135  EWR    PHL  23       80       21
25      86       EV      3271   N14923  EWR    PHL  31       80       21
26      93       EV      4619   N14562  EWR    PHL  26       80       21
27     -17       EV      4616   N14153  EWR    PHL  27       80       16
28     -11       EV      4619   N13969  EWR    PHL  29       80       21
29      35       EV      4619   N13550  EWR    PHL  36       80       21
30      -4       EV      4619   N13538  EWR    PHL  25       80       21
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
336747 -21       HA      51     N389HA  JFK    HNL  594      4983     10
336748  -2       HA      51     N385HA  JFK    HNL  614      4983     10
336749  -9       HA      51     N380HA  JFK    HNL  613      4983     10
336750 -12       HA      51     N389HA  JFK    HNL  612      4983     10
336751   8       HA      51     N385HA  JFK    HNL  593      4983     10
336752 -22       HA      51     N390HA  JFK    HNL  607      4983     10
336753 -20       HA      51     N381HA  JFK    HNL  604      4983     10
336754 -27       HA      51     N384HA  JFK    HNL  589      4983     10
336755 -44       HA      51     N388HA  JFK    HNL  597      4983     10
336756 -21       HA      51     N382HA  JFK    HNL  616      4983     10
336757 -46       HA      51     N393HA  JFK    HNL  582      4983     10
336758 -38       HA      51     N380HA  JFK    HNL  593      4983     10
336759 -32       HA      51     N383HA  JFK    HNL  595      4983     10
336760 -18       HA      51     N389HA  JFK    HNL  609      4983     10
336761 -43       HA      51     N383HA  JFK    HNL  601      4983     10
336762 -26       HA      51     N380HA  JFK    HNL  604      4983     10
336763 -29       HA      51     N388HA  JFK    HNL  605      4983     10
336764 -28       HA      51     N382HA  JFK    HNL  605      4983     10
336765  -3       HA      51     N391HA  JFK    HNL  615      4983     10
336766   7       HA      51     N389HA  JFK    HNL  630      4983     10
336767   2       HA      51     N389HA  JFK    HNL  632      4983     10
336768  -4       HA      51     N385HA  JFK    HNL  625      4983     10
336769 -19       HA      51     N382HA  JFK    HNL  605      4983     10
336770  -6       HA      51     N386HA  JFK    HNL  626      4983     10
336771  -8       HA      51     N388HA  JFK    HNL  616      4983     10
336772  23       HA      51     N389HA  JFK    HNL  636      4983     10
336773  -3       HA      51     N390HA  JFK    HNL  629      4983     10
336774 -33       HA      51     N391HA  JFK    HNL  584      4983     10
336775 -40       HA      51     N384HA  JFK    HNL  580      4983     10
336776  -7       HA      51     N392HA  JFK    HNL  603      4983     10
       minute time_hour
1       6     2013-07-27 01:00:00
2      29     2013-01-03 21:00:00
3       0     2013-01-04 12:00:00
4      15     2013-01-04 16:00:00
5      29     2013-01-04 21:00:00
6       0     2013-01-05 12:00:00
7      29     2013-01-06 21:00:00
8      29     2013-01-07 21:00:00
9      30     2013-01-08 21:00:00
10     29     2013-01-09 21:00:00
11     29     2013-01-10 21:00:00
12     29     2013-01-11 21:00:00
13     17     2013-01-12 16:00:00
14     29     2013-01-13 21:00:00
15     29     2013-01-14 21:00:00
16     30     2013-01-15 21:00:00
17     29     2013-01-16 21:00:00
18     29     2013-01-17 21:00:00
19     29     2013-01-18 21:00:00
20     17     2013-01-19 16:00:00
21     29     2013-01-20 21:00:00
22     29     2013-01-21 21:00:00
23     30     2013-01-22 21:00:00
24     29     2013-01-23 21:00:00
25     29     2013-01-24 21:00:00
26     29     2013-01-25 21:00:00
27     17     2013-01-26 16:00:00
28     29     2013-01-27 21:00:00
29     29     2013-01-28 21:00:00
30     30     2013-01-29 21:00:00
⋮      ⋮      ⋮
336747 0      2013-08-27 10:00:00
336748 0      2013-08-28 10:00:00
336749 0      2013-08-29 10:00:00
336750 0      2013-08-30 10:00:00
336751 0      2013-08-31 10:00:00
336752 0      2013-09-01 10:00:00
336753 0      2013-09-02 10:00:00
336754 0      2013-09-03 10:00:00
336755 0      2013-09-04 10:00:00
336756 0      2013-09-05 10:00:00
336757 0      2013-09-06 10:00:00
336758 0      2013-09-07 10:00:00
336759 0      2013-09-08 10:00:00
336760 0      2013-09-09 10:00:00
336761 0      2013-09-10 10:00:00
336762 0      2013-09-11 10:00:00
336763 0      2013-09-13 10:00:00
336764 0      2013-09-14 10:00:00
336765 0      2013-09-15 10:00:00
336766 0      2013-09-16 10:00:00
336767 0      2013-09-18 10:00:00
336768 0      2013-09-20 10:00:00
336769 0      2013-09-21 10:00:00
336770 0      2013-09-22 10:00:00
336771 0      2013-09-23 10:00:00
336772 0      2013-09-25 10:00:00
336773 0      2013-09-27 10:00:00
336774 0      2013-09-28 10:00:00
336775 0      2013-09-29 10:00:00
336776 0      2013-09-30 10:00:00

In [20]:
flights |> arrange(desc(distance / air_time)) #Fastest flight

       year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
1      2013  5    25  1709     1700             9       1923     1937
2      2013  7     2  1558     1513            45       1745     1719
3      2013  5    13  2040     2025            15       2225     2226
4      2013  3    23  1914     1910             4       2045     2043
5      2013  1    12  1559     1600            -1       1849     1917
6      2013 11    17   650      655            -5       1059     1150
7      2013  2    21  2355     2358            -3        412      438
8      2013 11    17   759      800            -1       1212     1255
9      2013 11    16  2003     1925            38         17       36
10     2013 11    16  2349     2359           -10        402      440
11     2013 11    17   851      855            -4       1307     1345
12     2013 11    17  1926     1925             1          7       39
13     2013 12     5  1858     1900            -2       2313     2359
14     2013  2    10  1658     1700            -2       2125     2204
15     2013  2    10  1958     1855            63         31     2355
16     2013 11    17   554      600            -6       1012     1043
17     2013 11    17  1455     1455             0       1915     1951
18     2013  2    13  1548     1555            -7       2030     2055
19     2013  2    21  1916     1855            21       2400     2355
20     2013  3     9  2317     2155            82        344      242
21     2013 11    17   923      920             3       1351     1429
22     2013  9    29  1359     1343            16       1523     1545
23     2013 11    16  2055     2050             5        105      135
24     2013 11    15   854      855            -1       1325     1345
25     2013 12     5  1628     1630            -2       2045     2130
26     2013  2    11   610      610             0       1033     1050
27     2013  2    11   824      830            -6       1257     1335
28     2013  2    11  1726     1700            26       2147     2204
29     2013  2    21  1710     1700            10       2129     2204
30     2013  2    21  2158     2145            13        215      232
⋮      ⋮    ⋮     ⋮   ⋮        ⋮              ⋮         ⋮        ⋮
336747 2013 9     25    NA     1655            NA         NA     1840
336748 2013 9     25    NA     1559            NA         NA     1719
336749 2013 9     26  1331     1329             2       1923     1813
336750 2013 9     26    NA      915            NA         NA     1141
336751 2013 9     26    NA     1400            NA         NA     1512
336752 2013 9     26    NA     1240            NA         NA     1525
336753 2013 9     27  1332     1329             3       1629     1509
336754 2013 9     27  2253     1945           188         NA     2146
336755 2013 9     27    NA      600            NA         NA      730
336756 2013 9     27    NA     2100            NA         NA     2211
336757 2013 9     27    NA     1329            NA         NA     1444
336758 2013 9     27    NA     1600            NA         NA     1739
336759 2013 9     28   555      600            -5        953      753
336760 2013 9     28   847      839             8       1130      959
336761 2013 9     28  1010     1020           -10       1344     1222
336762 2013 9     28  1214     1225           -11       1801     1510
336763 2013 9     28    NA     1803            NA         NA     1927
336764 2013 9     28    NA      910            NA         NA     1220
336765 2013 9     28    NA     1635            NA         NA     1827
336766 2013 9     29  1734     1711            23       2159     2020
336767 2013 9     29    NA     2054            NA         NA     2302
336768 2013 9     29    NA     1830            NA         NA     2010
336769 2013 9     29    NA      700            NA         NA      833
336770 2013 9     30   559      600            -1         NA      715
336771 2013 9     30    NA     1842            NA         NA     2019
336772 2013 9     30    NA     1455            NA         NA     1634
336773 2013 9     30    NA     2200            NA         NA     2312
336774 2013 9     30    NA     1210            NA         NA     1330
336775 2013 9     30    NA     1159            NA         NA     1344
336776 2013 9     30    NA      840            NA         NA     1020
       arr_delay carrier flight tailnum origin dest air_time distance hour
1      -14       DL      1499   N666DN  LGA    ATL   65       762     17
2       26       EV      4667   N17196  EWR    MSP   93      1008     15
3       -1       EV      4292   N14568  EWR    GSP   55       594     20
4        2       EV      3805   N12567  EWR    BNA   70       748     19
5      -28       DL      1902   N956DL  LGA    PBI  105      1035     16
6      -51       DL       315   N3768   JFK    SJU  170      1598      6
7      -26       B6       707   N779JB  JFK    SJU  172      1598     23
8      -43       AA       936   N5FFAA  JFK    STT  175      1623      8
9      -19       DL       347   N3773D  JFK    SJU  173      1598     19
10     -38       B6      1503   N571JB  JFK    SJU  173      1598     23
11     -38       DL       301   N624AG  JFK    SJU  173      1598      8
12     -32       DL       347   N382DA  JFK    SJU  173      1598     19
13     -46       AA      1029   N617AA  JFK    SJU  173      1598     19
14     -39       DL       329   N371DA  JFK    SJU  173      1598     17
15      36       AA      1613   N625AA  JFK    SJU  173      1598     18
16     -31       B6      1403   N641JB  JFK    SJU  174      1598      6
17     -36       DL         1   N3751B  JFK    SJU  174      1598     14
18     -25       B6       703   N579JB  JFK    SJU  174      1598     15
19       5       AA      1613   N5DMAA  JFK    SJU  174      1598     18
20      62       B6       713   N584JB  JFK    SJU  174      1598     21
21     -38       UA      1519   N27724  EWR    STT  178      1634      9
22     -22       EV      4687   N11544  EWR    CVG   62       569     13
23     -30       UA      1071   N37281  EWR    BQN  173      1585     20
24     -20       DL       301   N723TW  JFK    SJU  175      1598      8
25     -45       AA        95   N5EHAA  JFK    SJU  175      1598     16
26     -17       B6       709   N612JB  JFK    SJU  175      1598      6
27     -38       DL       301   N654DL  JFK    SJU  175      1598      8
28     -17       DL       329   N3754A  JFK    SJU  175      1598     17
29     -35       DL       329   N3752   JFK    SJU  175      1598     17
30     -17       B6       701   N198JB  JFK    SJU  175      1598     21
⋮      ⋮         ⋮       ⋮      ⋮       ⋮      ⋮    ⋮        ⋮        ⋮
336747 NA        MQ      3411   N735MQ  LGA    RDU  NA        431     16
336748 NA        MQ      3748   N530MQ  EWR    ORD  NA        719     15
336749 NA        UA        15   N67052  EWR    HNL  NA       4963     13
336750 NA        EV      5109   N748EV  LGA    CHS  NA        641      9
336751 NA        US      2183   NA      LGA    DCA  NA        214     14
336752 NA        WN      4720   N691WN  EWR    HOU  NA       1411     12
336753 NA        AA       331   N565AA  LGA    ORD  NA        733     13
336754 NA        EV      5306   N605QX  LGA    GSO  NA        461     19
336755 NA        AA       301   N584AA  LGA    ORD  NA        733      6
336756 NA        US      2164   NA      LGA    BOS  NA        184     21
336757 NA        MQ      3760   N505MQ  EWR    ORD  NA        719     13
336758 NA        UA       269   NA      LGA    ORD  NA        733     16
336759 NA        EV      5068   N133EV  EWR    DTW  NA        488      6
336760 NA        EV      4510   N14542  EWR    MKE  NA        725      8
336761 NA        EV      4412   N12175  EWR    DSM  NA       1017     10
336762 NA        AA       300   N488AA  EWR    DFW  NA       1372     12
336763 NA        EV      5563   N724EV  LGA    BTV  NA        258     18
336764 NA        AA         1   N320AA  JFK    LAX  NA       2475      9
336765 NA        US       581   NA      EWR    CLT  NA        529     16
336766 NA        UA       327   N463UA  EWR    PDX  NA       2434     17
336767 NA        EV      4536   N13988  EWR    CVG  NA        569     20
336768 NA        MQ      3134   N508MQ  EWR    ORD  NA        719     18
336769 NA        UA       331   NA      LGA    ORD  NA        733      7
336770 NA        WN       464   N411WN  EWR    MDW  NA        711      6
336771 NA        EV      5274   N740EV  LGA    BNA  NA        764     18
336772 NA        9E      3393   NA      JFK    DCA  NA        213     14
336773 NA        9E      3525   NA      LGA    SYR  NA        198     22
336774 NA        MQ      3461   N535MQ  LGA    BNA  NA        764     12
336775 NA        MQ      3572   N511MQ  LGA    CLE  NA        419     11
336776 NA        MQ      3531   N839MQ  LGA    RDU  NA        431      8
       minute time_hour
1       0     2013-05-25 17:00:00
2      13     2013-07-02 15:00:00
3      25     2013-05-13 20:00:00
4      10     2013-03-23 19:00:00
5       0     2013-01-12 16:00:00
6      55     2013-11-17 06:00:00
7      58     2013-02-21 23:00:00
8       0     2013-11-17 08:00:00
9      25     2013-11-16 19:00:00
10     59     2013-11-16 23:00:00
11     55     2013-11-17 08:00:00
12     25     2013-11-17 19:00:00
13      0     2013-12-05 19:00:00
14      0     2013-02-10 17:00:00
15     55     2013-02-10 18:00:00
16      0     2013-11-17 06:00:00
17     55     2013-11-17 14:00:00
18     55     2013-02-13 15:00:00
19     55     2013-02-21 18:00:00
20     55     2013-03-09 21:00:00
21     20     2013-11-17 09:00:00
22     43     2013-09-29 13:00:00
23     50     2013-11-16 20:00:00
24     55     2013-11-15 08:00:00
25     30     2013-12-05 16:00:00
26     10     2013-02-11 06:00:00
27     30     2013-02-11 08:00:00
28      0     2013-02-11 17:00:00
29      0     2013-02-21 17:00:00
30     45     2013-02-21 21:00:00
⋮      ⋮      ⋮
336747 55     2013-09-25 16:00:00
336748 59     2013-09-25 15:00:00
336749 29     2013-09-26 13:00:00
336750 15     2013-09-26 09:00:00
336751  0     2013-09-26 14:00:00
336752 40     2013-09-26 12:00:00
336753 29     2013-09-27 13:00:00
336754 45     2013-09-27 19:00:00
336755  0     2013-09-27 06:00:00
336756  0     2013-09-27 21:00:00
336757 29     2013-09-27 13:00:00
336758  0     2013-09-27 16:00:00
336759  0     2013-09-28 06:00:00
336760 39     2013-09-28 08:00:00
336761 20     2013-09-28 10:00:00
336762 25     2013-09-28 12:00:00
336763  3     2013-09-28 18:00:00
336764 10     2013-09-28 09:00:00
336765 35     2013-09-28 16:00:00
336766 11     2013-09-29 17:00:00
336767 54     2013-09-29 20:00:00
336768 30     2013-09-29 18:00:00
336769  0     2013-09-29 07:00:00
336770  0     2013-09-30 06:00:00
336771 42     2013-09-30 18:00:00
336772 55     2013-09-30 14:00:00
336773  0     2013-09-30 22:00:00
336774 10     2013-09-30 12:00:00
336775 59     2013-09-30 11:00:00
336776 40     2013-09-30 08:00:00

In [22]:
#Was there a flight on every day of 2013?
flights |> count(month, day, year)
#Yep

    month day year n
1   1      1  2013 842
2   1      2  2013 943
3   1      3  2013 914
4   1      4  2013 915
5   1      5  2013 720
6   1      6  2013 832
7   1      7  2013 933
8   1      8  2013 899
9   1      9  2013 902
10  1     10  2013 932
11  1     11  2013 930
12  1     12  2013 690
13  1     13  2013 828
14  1     14  2013 928
15  1     15  2013 894
16  1     16  2013 901
17  1     17  2013 927
18  1     18  2013 924
19  1     19  2013 674
20  1     20  2013 786
21  1     21  2013 912
22  1     22  2013 890
23  1     23  2013 897
24  1     24  2013 925
25  1     25  2013 922
26  1     26  2013 680
27  1     27  2013 823
28  1     28  2013 923
29  1     29  2013 890
30  1     30  2013 900
⋮   ⋮     ⋮   ⋮    ⋮
336 12     2  2013 1004
337 12     3  2013  973
338 12     4  2013  958
339 12     5  2013  969
340 12     6  2013  970
341 12     7  2013  691
342 12     8  2013  875
343 12     9  2013  962
344 12    10  2013  943
345 12    11  2013  954
346 12    12  2013  968
347 12    13  2013  970
348 12    14  2013  692
349 12    15  2013  880
350 12    16  2013  964
351 12    17  2013  949
352 12    18  2013  956
353 12    19  2013  974
354 12    20  2013  980
355 12    21  2013  811
356 12    22  2013  895
357 12    23  2013  985
358 12    24  2013  761
359 12    25  2013  719
360 12    26  2013  936
361 12    27  2013  963
362 12    28  2013  814
363 12    29  2013  888
364 12    30  2013  968
365 12    31  2013  776